export const LOGIN_REQUEST='LOGIN_REQUEST';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';

export const REGISTER_USER_REQUEST='REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS='REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL='REGISTER_USER_FAIL';


export const LOAD_USER_REQUEST='LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS='LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL='LOAD_USER_FAIL';


export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';
export const LOGOUT_FAIL='LOGOUT_FAIL';


export const All_USERS_REQUEST='All_USERS_REQUEST';
export const All_USERS_SUCCESS='All_USERS_SUCCESS';
export const All_USERS_FAIL='All_USERS_FAIL';



export const UPDATE_USER_REQUEST='UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS='UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL='UPDATE_USER_FAIL';
export const UPDATE_USER_RESET='UPDATE_USER_RESET';


export const DELETE_USER_REQUEST='DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS='DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL='DELETE_USER_FAIL';
export const DELETE_USER_RESET='DELETE_USER_RESET';

export const ADD_USER_REQUEST='ADD_USER_REQUEST';
export const ADD_USER_SUCCESS='ADD_USER_SUCCESS';
export const ADD_USER_FAIL='ADD_USER_FAIL';
export const ADD_USER_RESET='ADD_USER_RESET';

export const GOOGLE_USER_REQUEST='GOOGLE_USER_REQUEST';
export const GOOGLE_USER_SUCCESS='GOOGLE_USER_SUCCESS';
export const GOOGLE_USER_FAIL='GOOGLE_USER_FAIL';


export const CLEAR_ERRORS='CLEAR_ERRORS';
